'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useStore } from '@/store/useStore';
import { useToast } from '@/components/ui/ToastProvider';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { GeneratedTaskPreview } from '@/components/tasks/GeneratedTaskPreview';
import { createProject as apiCreateProject, assignTasks as apiAssignTasks, genId } from '@/lib/api';
import type { Task, AuditLog } from '@/types';

// Mock tasks generated by Architect agent (used as fallback / demo)
function mockGeneratedTasks(projectName: string): Task[] {
  const defs = [
    { name: 'Requirements Analysis & Architecture', priority: 'high'   as const, deps: [],          estimate: '2 days' },
    { name: 'Database Schema Design',               priority: 'high'   as const, deps: ['t1'],       estimate: '1 day'  },
    { name: 'Authentication & Authorization',        priority: 'high'   as const, deps: ['t1', 't2'], estimate: '3 days' },
    { name: 'Core Feature Development',              priority: 'medium' as const, deps: ['t3'],       estimate: '5 days' },
    { name: 'API Integration Layer',                 priority: 'medium' as const, deps: ['t2'],       estimate: '2 days' },
    { name: 'Frontend UI Components',                priority: 'medium' as const, deps: ['t3'],       estimate: '4 days' },
    { name: 'Testing & QA',                          priority: 'low'    as const, deps: ['t4','t5','t6'], estimate: '2 days' },
    { name: 'Deployment & DevOps',                   priority: 'low'    as const, deps: ['t7'],       estimate: '1 day'  },
  ];

  return defs.map((d, i) => ({
    id: `t${i + 1}`,
    name: d.name,
    assignee: '',
    avatar: '?',
    avatarColor: 'cyan',
    status: 'todo',
    priority: d.priority,
    project: projectName,
    deps: d.deps,
    estimate: d.estimate,
  }));
}

export default function CreateProjectPage() {
  const router = useRouter();
  const { showToast } = useToast();
  const { addTasks, setCurrentProjectId, prependLog, setLoading, fetchTasks } = useStore();

  const [name,     setName]     = useState('');
  const [desc,     setDesc]     = useState('');
  const [team,     setTeam]     = useState('');
  const [deadline, setDeadline] = useState('');

  const [generatedTasks, setGeneratedTasks] = useState<Task[]>([]);
  const [projectId,      setProjectId]      = useState<string | null>(null);
  const [phase,          setPhase]          = useState<'form' | 'tasks' | 'done'>('form');

  /* ── Step 1: Create project → Architect Agent generates tasks ── */
  async function handleCreateProject() {
    if (!name.trim() || !desc.trim()) {
      showToast('error', '✗ Project name and description are required');
      return;
    }

    setLoading(true, 'ARCHITECT AGENT GENERATING TASKS...');

    const teamArr = team.split(',').map((t) => t.trim()).filter(Boolean);

    const res = await apiCreateProject({ name, description: desc, team: teamArr, deadline });

    setLoading(false);

    let tasks: Task[];
    let pid: string;

    if (res.success && res.data) {
      tasks = res.data.tasks;
      pid   = res.data.projectId;
      if (res.data.logs) {
        res.data.logs.forEach((l) => prependLog(l));
      }
    } else {
      // Demo fallback
      tasks = mockGeneratedTasks(name);
      pid   = genId();

      const log: AuditLog = {
        id: genId(), agent: 'ARCHITECT', action: 'TASK_GENERATE',
        timestamp: new Date().toLocaleString(),
        reason: `Generated ${tasks.length} tasks for project "${name}". Analyzed description, identified dependencies, mapped feature graph. (Demo mode)`,
      };
      prependLog(log);
    }

    setGeneratedTasks(tasks);
    setProjectId(pid);
    setCurrentProjectId(pid);
    setPhase('tasks');
    showToast('success', `✓ ${tasks.length} tasks generated for "${name}"`);
  }

  /* ── Step 2: Assign tasks → Orchestrator Agent ── */
  async function handleAssignTasks() {
    if (!projectId) return;
    setLoading(true, 'ORCHESTRATOR ASSIGNING TASKS...');

    const res = await apiAssignTasks({ projectId });

    setLoading(false);

    if (res.success && res.data) {
      if (res.data.logs) {
        res.data.logs.forEach((l) => prependLog(l));
      }
      await fetchTasks();
    } else {
      const log: AuditLog = {
        id: genId(), agent: 'ORCHESTRATOR', action: 'TASK_ASSIGN',
        timestamp: new Date().toLocaleString(),
        reason: 'Assigned all generated tasks based on XP scores, domain expertise, and current workload. Balanced distribution. (Demo mode)',
      };
      prependLog(log);
      
      const mockTeam = ['alex', 'priya', 'sam'];
      const assignedDemoTasks = generatedTasks.map((t, i) => ({
        ...t,
        assignee: mockTeam[i % mockTeam.length],
        status: 'todo' as const
      }));
      addTasks(assignedDemoTasks);
    }

    setPhase('done');
    showToast('success', '✓ Tasks assigned by Orchestrator Agent');
  }

  return (
    <div>
      <PageHeader
        title="New Project"
        subtitle="// ARCHITECT AGENT WILL GENERATE TASKS"
        badge="AI-POWERED"
      />

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
        {/* ── Form ── */}
        <Card>
          <CardHeader title="＋ Project Setup" />

          <FormGroup label="Project Name">
            <input
              className="form-input"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="e.g. E-Commerce Platform v2"
              disabled={phase !== 'form'}
              style={inputStyle}
            />
          </FormGroup>

          <FormGroup label="Description">
            <textarea
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
              placeholder="Describe your project goals, tech stack, and scope. The Architect Agent will generate tasks based on this..."
              disabled={phase !== 'form'}
              rows={5}
              style={{ ...inputStyle, resize: 'vertical' }}
            />
          </FormGroup>

          <FormGroup label="Team Members (comma separated)">
            <input
              type="text"
              value={team}
              onChange={(e) => setTeam(e.target.value)}
              placeholder="e.g. priya, rahul, aisha, dev"
              disabled={phase !== 'form'}
              style={inputStyle}
            />
          </FormGroup>

          <FormGroup label="Deadline">
            <input
              type="date"
              value={deadline}
              onChange={(e) => setDeadline(e.target.value)}
              disabled={phase !== 'form'}
              style={inputStyle}
            />
          </FormGroup>

          {phase === 'form' && (
            <Button variant="primary" fullWidth onClick={handleCreateProject}>
              ⬡ Launch Architect Agent
            </Button>
          )}

          {phase === 'tasks' && (
            <Button variant="primary" fullWidth onClick={handleAssignTasks}>
              ◈ Run Orchestrator — Assign Tasks
            </Button>
          )}

          {phase === 'done' && (
            <Button variant="success" fullWidth onClick={() => router.push('/tasks')}>
              ✓ View Task Board
            </Button>
          )}

          <div
            style={{
              marginTop: 10, fontSize: 10, color: 'var(--text-muted)',
              fontFamily: 'var(--font-mono)', textAlign: 'center',
            }}
          >
            {phase === 'form'  && 'Gemini AI will break project into tasks automatically'}
            {phase === 'tasks' && 'Review generated tasks, then run Orchestrator to assign them'}
            {phase === 'done'  && 'Project created and tasks assigned successfully ✓'}
          </div>
        </Card>

        {/* ── AI Generated Tasks Preview ── */}
        <Card>
          <CardHeader
            title="🤖 AI Generated Tasks"
            action={
              generatedTasks.length > 0 ? (
                <Badge variant="cyan">{generatedTasks.length} TASKS</Badge>
              ) : undefined
            }
          />
          <GeneratedTaskPreview tasks={generatedTasks} />
        </Card>
      </div>
    </div>
  );
}

/* ── Local helpers ── */
function FormGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 18 }}>
      <label
        style={{
          display: 'block', fontSize: 10, color: 'var(--text-secondary)',
          fontFamily: 'var(--font-mono)', letterSpacing: 2,
          marginBottom: 8, textTransform: 'uppercase',
        }}
      >
        {label}
      </label>
      {children}
    </div>
  );
}

const inputStyle: React.CSSProperties = {
  width: '100%', background: 'var(--bg-deep)',
  border: '1px solid var(--border)', borderRadius: 6,
  padding: '10px 14px', color: 'var(--text-primary)',
  fontFamily: 'var(--font-mono)', fontSize: 12, outline: 'none',
};
